name: tb_ntb_app_dev

channels:
  - defaults
  - simpleitk
  - conda-forge
dependencies:
  - python=3.8.0 
  - SimpleITK>=2.0.0
  - scikit-learn>=0.24.0
  - matplotlib
  - numpy
  - pandas
  - docutils #used for converting rst to html
  - PySide2
  - requests
  - flake8 #only used for development, test code formatting
  - pip
  - pip:
    - black #only used for development, code formatting
    - QDarkStyle #dark stylesheet for Qt applications
