name: tb_ntb_app

channels:
  - defaults
  - simpleitk
  - conda-forge
dependencies:
  - python=3.8.0 
  - SimpleITK>=2.0.0
  - scikit-learn>=0.24.0
  - matplotlib
  - numpy
  - pandas
  - docutils #used for converting rst to html
  - PySide6
  - requests
  - pip
  - pip:
    - QDarkStyle #dark stylesheet for Qt applications
    - git+https://github.com/SimpleITK/SimpleITKUtilities
