name: RAP TB/not-TB Frontend Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # The specific pre-commit tests configurations are found in
  # the .pre-commit-config.yaml file at the root of the repository
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - name: pre-commit
      uses: pre-commit/action@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    # run trufflehog3 with no-entropy because the sample images are
    # stored with git-lfs and those files contain the sha256 instead of the
    # actual image. The sha's are all high entropy
    - name: trufflehog3 secrets scanner
      run: |
        python -m pip install trufflehog3
        trufflehog3 -v --no-entropy . && echo "tufflehog3 secrets scan passed"
